version: "3.7"
services:
  workspace:
    container_name: workspace
    build: 
      context: ./workspace
    ports:
      - 80:80
      - 443:443
    privileged: true
    volumes:
      - ./workspace/project:/go/src/app
    links:
      - mysql
      - postgresql
      - mongodb
    ports:
      - "9090:9090"
  mysql:
    container_name: mysql
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - 23306:3306
    volumes:
      - ./mysql/data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: test
      MYSQL_PASSWORD: test
  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin/phpmyadmin
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOSTS=db
      - PMA_USER=root
      - PMA_PASSWORD=root
    ports:
      - 8080:80
  postgresql:
    container_name: postgresql
    image: postgres:12-alpine
    volumes:
      - ./postgresql/data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: secret
    ports:
      - 5432:5432
  mongodb:
    image: mongo:4.2.2
    container_name: mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - './mongodb/data:/data/db'
    ports:
      - '27017:27017'
    command: mongod --smallfiles  
  mongo-express:
    container_name: mongo-express
    links:
      - 'mongodb:mongo'
    ports:
      - '8081:8081'
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
    image: mongo-express