version: "3.7"
services:
  workspace:
    container_name: workspace
    build:
      context: ./workspace
    ports:
      - 80:80
      - 443:443
    privileged: true
    volumes:
      - ./workspace/project:/go/src/app
      - ./sqlite/data:/tmp
    links:
      - mysql
      - postgres
    tty: true
  mysql:
    container_name: mysql
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - 23306:3306
    volumes:
      - ./mysql/data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: test
      MYSQL_PASSWORD: test
  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin/phpmyadmin
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOSTS=mysql
      - PMA_USER=root
      - PMA_PASSWORD=root
    ports:
      - 8089:80
  postgres:
    container_name: postgres
    image: postgres:12-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: db
      PGDATA: /tmp
    volumes:
      - ./postgresql/data:/var/lib/postgresql/data
    ports:
      - 5432:5432